backend:
  name: git-gateway
  branch: master
media_folder: "static/assets/images/uploads"
public_folder: "static/assets/images/uploads"
collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Alt Title", name: "altTitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Order", name: "rating", widget: "number"}
      - {label: "Badges", name: "badges", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}