backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/assets/images/uploads"
public_folder: "static/assets/images/uploads"
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Alt Title", name: "altTitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Order", name: "rating", widget: "number"}
      - {label: "Badges", name: "badges", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: "projects"
  - label: "Experience"
    folder: "src/content/experience"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "experience"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Start Date", name: "start_date", widget: "datetime"}
      - {label: "End Date", name: "end_date", widget: "datetime"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Location", name: "location", widget: "map"}
      - {label: "Body", name: "body", widget: "markdown"}